### ISSUE TITLE
Change Configuration Directories

### ISSUE THREAD

**Issue by MattSurabian** [MattSurabian/proxpn-bash-client#17]
Currently `sudo` perms are required for installation because configuration files live in `/etc/proxpn/`. This could make it harder to distribute via package managers that prefer to avoid using `root` perms like homebrew. It probably makes sense to utilize `/usr/local/etc` or better yet `~/.proxpn`.

Version 3 here we come. :fireworks:

**Comment by Pysis868** [comment]
How about `~/.config/proxpn/*`?

**Comment by MattSurabian** [comment]
Yep, that works for me
