### ISSUE TITLE
Ubuntu issue

### ISSUE THREAD

**Issue by ryoishikawa74** [MattSurabian/proxpn-bash-client#19]
Hi there ... I did all the steps and double checked everything ... maybe I'm missing something I donw know. Whenever I try to use the proxpn command (as root) and choose any server from the list, I get this message:

Running:
/usr/sbin/openvpn --config "/etc/proxpn/proxpn.ovpn" --remote "mfl1.proxpn.com" 443 --auth-user-pass "/etc/proxpn/login.conf" --auth-nocache

Options error: In [CMD-LINE]:1: Error opening configuration file: "/etc/proxpn/proxpn.ovpn"
Use --help for more information.

Any ideas of what could it be?
Thanks!

**Comment by MattSurabian** [comment]
Hmmmm, could you paste the output of `sudo cat /etc/proxpn/proxpn.ovpn` and `sudo ls -la /etc/proxpn/`

**Comment by MattSurabian** [comment]
Sorry about that, I figured out the issue and just pushed a hotfix to master in #20

**Comment by ryoishikawa74** [comment]
Thanks a lot Matt! I'll test it today when I get home :+1:
