### ISSUE TITLE
Auth error,  won't connect to proxpn

### ISSUE THREAD

**Issue by djpadbit** [MattSurabian/proxpn-bash-client#28]
When I try to connect to proxpn it won't work with a auth error

pablo@Pablo-Pc-Kali:~$ sudo proxpn

Welcome to the ProXPN OpenVPN Bash Client!

Which exit node would you like to use?
1) Chicago    4) London    7) Prague       10) SanJose
2) Netherlands    5) LA        8) Seattle
3) BASIC      6) Stockholm     9) Miami
Select an exit node (1-10): 5

Running:
/usr/sbin/openvpn --config /home/pablo/.config/proxpn/proxpn.ovpn --remote la1.proxpn.com 443 --auth-nocache --auth-user-pass /home/pablo/.config/proxpn/login.conf

Sat Jan  9 18:43:34 2016 us=450881 Current Parameter Settings:
Sat Jan  9 18:43:34 2016 us=450982   config = '/home/pablo/.config/proxpn/proxpn.ovpn'
Sat Jan  9 18:43:34 2016 us=451007   mode = 0
Sat Jan  9 18:43:34 2016 us=451027   persist_config = DISABLED
Sat Jan  9 18:43:34 2016 us=451044   persist_mode = 1
Sat Jan  9 18:43:34 2016 us=451061 NOTE: --mute triggered...
Sat Jan  9 18:43:34 2016 us=451091 270 variation(s) on previous 5 message(s) suppressed by --mute
Sat Jan  9 18:43:34 2016 us=451116 OpenVPN 2.3.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Dec  1 2014
Sat Jan  9 18:43:34 2016 us=451141 library versions: OpenSSL 1.0.1k 8 Jan 2015, LZO 2.08
Sat Jan  9 18:43:34 2016 us=452280 LZO compression initialized
Sat Jan  9 18:43:34 2016 us=452410 Control Channel MTU parms [ L:1544 D:140 EF:40 EB:0 ET:0 EL:0 ]
Sat Jan  9 18:43:34 2016 us=452473 Socket Buffers: R=[87380->131072] S=[16384->131072]
Sat Jan  9 18:43:34 2016 us=579477 Data Channel MTU parms [ L:1544 D:1450 EF:44 EB:135 ET:0 EL:0 AF:3/1 ]
Sat Jan  9 18:43:34 2016 us=579514 Local Options String: 'V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,cipher BF-CBC,auth SHA1,keysize 512,key-method 2,tls-client'
Sat Jan  9 18:43:34 2016 us=579523 Expected Remote Options String: 'V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_SERVER,comp-lzo,cipher BF-CBC,auth SHA1,keysize 512,key-method 2,tls-server'
Sat Jan  9 18:43:34 2016 us=579544 Local Options hash (VER=V4): '729fc673'
Sat Jan  9 18:43:34 2016 us=579559 Expected Remote Options hash (VER=V4): 'ce7b442d'
Sat Jan  9 18:43:34 2016 us=579576 Attempting to establish TCP connection with [AF_INET]64.27.29.67:443 [nonblock]
Sat Jan  9 18:43:35 2016 us=579723 TCP connection established with [AF_INET]64.27.29.67:443
Sat Jan  9 18:43:35 2016 us=579742 TCPv4_CLIENT link local: [undef]
Sat Jan  9 18:43:35 2016 us=579748 TCPv4_CLIENT link remote: [AF_INET]64.27.29.67:443
Sat Jan  9 18:43:35 2016 us=729349 TLS: Initial packet from [AF_INET]64.27.29.67:443, sid=78eb4006 02bd4451
Sat Jan  9 18:43:38 2016 us=69230 VERIFY OK: depth=1, C=US, ST=CA, L=SanFrancisco, O=proXPN Direct, LLC, OU=proxpn.com, CN=proxpn.com, name=proxpn.com, emailAddress=support@proxpn.com
Sat Jan  9 18:43:38 2016 us=69358 Validating certificate key usage
Sat Jan  9 18:43:38 2016 us=69363 ++ Certificate has key usage  00a0, expects 00a0
Sat Jan  9 18:43:38 2016 us=69365 VERIFY KU OK
Sat Jan  9 18:43:38 2016 us=69369 NOTE: --mute triggered...
Sat Jan  9 18:43:44 2016 us=400576 9 variation(s) on previous 5 message(s) suppressed by --mute
Sat Jan  9 18:43:44 2016 us=400590 [proxpn.com] Peer Connection Initiated with [AF_INET]64.27.29.67:443
Sat Jan  9 18:43:46 2016 us=461755 SENT CONTROL [proxpn.com]: 'PUSH_REQUEST' (status=1)
Sat Jan  9 18:43:47 2016 us=154283 AUTH: Received control message: AUTH_FAILED
Sat Jan  9 18:43:47 2016 us=154420 TCP/UDP: Closing socket
Sat Jan  9 18:43:47 2016 us=154455 SIGTERM[soft,auth-failure] received, process exiting

**Comment by MattSurabian** [comment]
I can confirm that the LA exit node currently works and allows me to connect with my username and password. Best I can guess there's something wrong with your credentials file `/home/pablo/.config/proxpn/login.conf`. Confirm that:
- The file exists
- The file has two lines, username on the first and password on the second.
- The username and password are correct

You can also try this command and see if your credentials are accepted when logging in normally:

```
/usr/sbin/openvpn --config /home/pablo/.config/proxpn/proxpn.ovpn --remote la1.proxpn.com 443 --auth-nocache --auth-user-pass
```

Let me know if any of this solves it, and good luck!

**Comment by djpadbit** [comment]
Thanks a lot for responding !

The file is there and it is username on the first line and password on the other and on the site the credentials work 
I tested it and it doesn't work with and without root

pablo@Pablo-Pc-Kali:~$ /usr/sbin/openvpn --config /home/pablo/.config/proxpn/proxpn.ovpn --remote la1.proxpn.com 443 --auth-nocache --auth-user-pass
Sun Jan 10 11:02:32 2016 us=812339 Current Parameter Settings:
Sun Jan 10 11:02:32 2016 us=812367   config = '/home/pablo/.config/proxpn/proxpn.ovpn'
Sun Jan 10 11:02:32 2016 us=812372   mode = 0
Sun Jan 10 11:02:32 2016 us=812376   persist_config = DISABLED
Sun Jan 10 11:02:32 2016 us=812380   persist_mode = 1
Sun Jan 10 11:02:32 2016 us=812384 NOTE: --mute triggered...
Sun Jan 10 11:02:32 2016 us=812391 270 variation(s) on previous 5 message(s) suppressed by --mute
Sun Jan 10 11:02:32 2016 us=812397 OpenVPN 2.3.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Dec  1 2014
Sun Jan 10 11:02:32 2016 us=812403 library versions: OpenSSL 1.0.1k 8 Jan 2015, LZO 2.08
Enter Auth Username: *******************
Enter Auth Password: ***********
Sun Jan 10 11:02:53 2016 us=309359 LZO compression initialized
Sun Jan 10 11:02:53 2016 us=309395 Control Channel MTU parms [ L:1544 D:140 EF:40 EB:0 ET:0 EL:0 ]
Sun Jan 10 11:02:53 2016 us=309411 Socket Buffers: R=[87380->131072] S=[16384->131072]
Sun Jan 10 11:02:53 2016 us=460539 Data Channel MTU parms [ L:1544 D:1450 EF:44 EB:135 ET:0 EL:0 AF:3/1 ]
Sun Jan 10 11:02:53 2016 us=460556 Local Options String: 'V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,cipher BF-CBC,auth SHA1,keysize 512,key-method 2,tls-client'
Sun Jan 10 11:02:53 2016 us=460560 Expected Remote Options String: 'V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_SERVER,comp-lzo,cipher BF-CBC,auth SHA1,keysize 512,key-method 2,tls-server'
Sun Jan 10 11:02:53 2016 us=460570 Local Options hash (VER=V4): '729fc673'
Sun Jan 10 11:02:53 2016 us=460575 Expected Remote Options hash (VER=V4): 'ce7b442d'
Sun Jan 10 11:02:53 2016 us=460584 Attempting to establish TCP connection with [AF_INET]64.27.29.67:443 [nonblock]
Sun Jan 10 11:02:54 2016 us=460715 TCP connection established with [AF_INET]64.27.29.67:443
Sun Jan 10 11:02:54 2016 us=460737 TCPv4_CLIENT link local: [undef]
Sun Jan 10 11:02:54 2016 us=460745 TCPv4_CLIENT link remote: [AF_INET]64.27.29.67:443
Sun Jan 10 11:02:54 2016 us=891920 TLS: Initial packet from [AF_INET]64.27.29.67:443, sid=45b8ff14 8d697c77
Sun Jan 10 11:02:57 2016 us=600514 VERIFY OK: depth=1, C=US, ST=CA, L=SanFrancisco, O=proXPN Direct, LLC, OU=proxpn.com, CN=proxpn.com, name=proxpn.com, emailAddress=support@proxpn.com
Sun Jan 10 11:02:57 2016 us=600643 Validating certificate key usage
Sun Jan 10 11:02:57 2016 us=600647 ++ Certificate has key usage  00a0, expects 00a0
Sun Jan 10 11:02:57 2016 us=600650 VERIFY KU OK
Sun Jan 10 11:02:57 2016 us=600653 NOTE: --mute triggered...
Sun Jan 10 11:03:06 2016 us=180035 4 variation(s) on previous 5 message(s) suppressed by --mute
Sun Jan 10 11:03:06 2016 us=180058 Connection reset, restarting [0]
Sun Jan 10 11:03:06 2016 us=180123 TCP/UDP: Closing socket
Sun Jan 10 11:03:06 2016 us=180141 SIGUSR1[soft,connection-reset] received, process restarting
Sun Jan 10 11:03:06 2016 us=180146 Restart pause, 5 second(s)
Sun Jan 10 11:03:11 2016 us=180252 Re-using SSL/TLS context
Sun Jan 10 11:03:11 2016 us=180276 LZO compression initialized
Sun Jan 10 11:03:11 2016 us=180306 Control Channel MTU parms [ L:1544 D:140 EF:40 EB:0 ET:0 EL:0 ]
Sun Jan 10 11:03:11 2016 us=180321 Socket Buffers: R=[87380->131072] S=[16384->131072]
Sun Jan 10 11:03:11 2016 us=683110 Data Channel MTU parms [ L:1544 D:1450 EF:44 EB:135 ET:0 EL:0 AF:3/1 ]
Sun Jan 10 11:03:11 2016 us=683131 Local Options String: 'V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,cipher BF-CBC,auth SHA1,keysize 512,key-method 2,tls-client'
Sun Jan 10 11:03:11 2016 us=683135 Expected Remote Options String: 'V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_SERVER,comp-lzo,cipher BF-CBC,auth SHA1,keysize 512,key-method 2,tls-server'
Sun Jan 10 11:03:11 2016 us=683146 Local Options hash (VER=V4): '729fc673'
Sun Jan 10 11:03:11 2016 us=683150 Expected Remote Options hash (VER=V4): 'ce7b442d'
Sun Jan 10 11:03:11 2016 us=683156 Attempting to establish TCP connection with [AF_INET]64.27.29.67:443 [nonblock]
Sun Jan 10 11:03:12 2016 us=683278 TCP connection established with [AF_INET]64.27.29.67:443
Sun Jan 10 11:03:12 2016 us=683295 TCPv4_CLIENT link local: [undef]
Sun Jan 10 11:03:12 2016 us=683300 TCPv4_CLIENT link remote: [AF_INET]64.27.29.67:443
Sun Jan 10 11:03:13 2016 us=118075 TLS: Initial packet from [AF_INET]64.27.29.67:443, sid=28383fb2 70486f52
Enter Auth Username: ******************
Enter Auth Password: ***********
Sun Jan 10 11:03:30 2016 us=590199 VERIFY OK: depth=1, C=US, ST=CA, L=SanFrancisco, O=proXPN Direct, LLC, OU=proxpn.com, CN=proxpn.com, name=proxpn.com, emailAddress=support@proxpn.com
Sun Jan 10 11:03:30 2016 us=590298 Validating certificate key usage
Sun Jan 10 11:03:30 2016 us=590302 ++ Certificate has key usage  00a0, expects 00a0
Sun Jan 10 11:03:30 2016 us=590305 VERIFY KU OK
Sun Jan 10 11:03:30 2016 us=590309 NOTE: --mute triggered...
Sun Jan 10 11:03:36 2016 us=389738 9 variation(s) on previous 5 message(s) suppressed by --mute
Sun Jan 10 11:03:36 2016 us=389751 [proxpn.com] Peer Connection Initiated with [AF_INET]64.27.29.67:443
Sun Jan 10 11:03:38 2016 us=708170 SENT CONTROL [proxpn.com]: 'PUSH_REQUEST' (status=1)
Sun Jan 10 11:03:39 2016 us=49766 AUTH: Received control message: AUTH_FAILED
Sun Jan 10 11:03:39 2016 us=49891 TCP/UDP: Closing socket
Sun Jan 10 11:03:39 2016 us=49928 SIGTERM[soft,auth-failure] received, process exiting
pablo@Pablo-Pc-Kali:~$ sudo /usr/sbin/openvpn --config /home/pablo/.config/proxpn/proxpn.ovpn --remote la1.proxpn.com 443 --auth-nocache --auth-user-pass
Sun Jan 10 11:07:04 2016 us=891127 Current Parameter Settings:
Sun Jan 10 11:07:04 2016 us=891151   config = '/home/pablo/.config/proxpn/proxpn.ovpn'
Sun Jan 10 11:07:04 2016 us=891157   mode = 0
Sun Jan 10 11:07:04 2016 us=891162   persist_config = DISABLED
Sun Jan 10 11:07:04 2016 us=891166   persist_mode = 1
Sun Jan 10 11:07:04 2016 us=891170 NOTE: --mute triggered...
Sun Jan 10 11:07:04 2016 us=891178 270 variation(s) on previous 5 message(s) suppressed by --mute
Sun Jan 10 11:07:04 2016 us=891182 OpenVPN 2.3.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Dec  1 2014
Sun Jan 10 11:07:04 2016 us=891189 library versions: OpenSSL 1.0.1k 8 Jan 2015, LZO 2.08
Enter Auth Username: ******************
Enter Auth Password: ***********
Sun Jan 10 11:07:18 2016 us=465379 LZO compression initialized
Sun Jan 10 11:07:18 2016 us=465415 Control Channel MTU parms [ L:1544 D:140 EF:40 EB:0 ET:0 EL:0 ]
Sun Jan 10 11:07:18 2016 us=465433 Socket Buffers: R=[87380->131072] S=[16384->131072]
Sun Jan 10 11:07:18 2016 us=639252 Data Channel MTU parms [ L:1544 D:1450 EF:44 EB:135 ET:0 EL:0 AF:3/1 ]
Sun Jan 10 11:07:18 2016 us=639272 Local Options String: 'V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,cipher BF-CBC,auth SHA1,keysize 512,key-method 2,tls-client'
Sun Jan 10 11:07:18 2016 us=639276 Expected Remote Options String: 'V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_SERVER,comp-lzo,cipher BF-CBC,auth SHA1,keysize 512,key-method 2,tls-server'
Sun Jan 10 11:07:18 2016 us=639288 Local Options hash (VER=V4): '729fc673'
Sun Jan 10 11:07:18 2016 us=639293 Expected Remote Options hash (VER=V4): 'ce7b442d'
Sun Jan 10 11:07:18 2016 us=639302 Attempting to establish TCP connection with [AF_INET]64.27.29.67:443 [nonblock]
Sun Jan 10 11:07:19 2016 us=639399 TCP connection established with [AF_INET]64.27.29.67:443
Sun Jan 10 11:07:19 2016 us=639413 TCPv4_CLIENT link local: [undef]
Sun Jan 10 11:07:19 2016 us=639416 TCPv4_CLIENT link remote: [AF_INET]64.27.29.67:443
Sun Jan 10 11:07:19 2016 us=789197 TLS: Initial packet from [AF_INET]64.27.29.67:443, sid=c780a57b 9358f86d
Sun Jan 10 11:07:21 2016 us=621774 VERIFY OK: depth=1, C=US, ST=CA, L=SanFrancisco, O=proXPN Direct, LLC, OU=proxpn.com, CN=proxpn.com, name=proxpn.com, emailAddress=support@proxpn.com
Sun Jan 10 11:07:21 2016 us=621903 Validating certificate key usage
Sun Jan 10 11:07:21 2016 us=621908 ++ Certificate has key usage  00a0, expects 00a0
Sun Jan 10 11:07:21 2016 us=621910 VERIFY KU OK
Sun Jan 10 11:07:21 2016 us=621914 NOTE: --mute triggered...
Sun Jan 10 11:07:26 2016 us=831467 9 variation(s) on previous 5 message(s) suppressed by --mute
Sun Jan 10 11:07:26 2016 us=831480 [proxpn.com] Peer Connection Initiated with [AF_INET]64.27.29.67:443
Sun Jan 10 11:07:29 2016 us=145851 SENT CONTROL [proxpn.com]: 'PUSH_REQUEST' (status=1)
Sun Jan 10 11:07:29 2016 us=475906 AUTH: Received control message: AUTH_FAILED
Sun Jan 10 11:07:29 2016 us=476041 TCP/UDP: Closing socket
Sun Jan 10 11:07:29 2016 us=476079 SIGTERM[soft,auth-failure] received, process exiting

**Comment by djpadbit** [comment]
Hello again ! I manage to make it work !

I got on to my windows install and installed the proxpn software and i saw that tcp doesn't work.Only upd worked (i don't know why by the way) so i got to the log of the software and got the ip were it was connecting (Chicago i think) the ip was : 196.52.21.65 on port 443, so i modified the script and added a new exit node and change in the proxpn.ovpn the line proto tcp to proto udp and it worked !!

**Comment by MattSurabian** [comment]
Could you open a pull request for this? It might help to explain what we noticed in #27

**Comment by MattSurabian** [comment]
I'm closing this issue for now, but if we get anymore information on this TCP/UDP change you had to make please reopen!
