### ISSUE TITLE
UDP?

### ISSUE THREAD

**Issue by BrianG61UK** [MattSurabian/proxpn-bash-client#32]
Your proxpn.ovpn file seems to be set up to use TCP.

Why would you cripple it like that?

Doesn't proxpn support UDP?

**Comment by MattSurabian** [comment]
There's an open PR in #30 to add UDP support so no worries, it's coming soon.

**Comment by MattSurabian** [comment]
I hope to complete the UDP work and ship it before the end of this weekend.

**Comment by MattSurabian** [comment]
see #33

**Comment by MattSurabian** [comment]
Shipped in [4.0.0](https://github.com/MattSurabian/proxpn-bash-client/releases/tag/4.0.0)
