### ISSUE TITLE
disable ipv6 when establishing connection

### ISSUE THREAD

**Issue by wmdiem** [MattSurabian/proxpn-bash-client#34]
It would be really nice if the script would disable ipv6 when establishing the connection. Many applications seem to bind to both ipv6 and 4, so without disabling v6, traffic might still go out from a traceable address (often more tracable, since ipv6 addresses aren't usually NATed), in cleartext.

In linux this can be done with: 

 echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6 

No idea how to do it in OSX. 

However, it seems like network manager tries to turn ipv6 back on when you do it this way. I've had to edit the connection in NM (setting ipv6 to ignore for the interface) in order to keep it off. There must be a global way to disable this programatically without fiddling with NM configs, but I don't know ATM what it is. 

And thanks for the script.

**Comment by MattSurabian** [comment]
In OS X I believe this can be done with `networksetup -setv6off Ethernet` `networksetup -setv6off Wi-Fi`. I'm not totally opposed to adding something like this to the script, but it seems like it might be a bit of an overreach. It would also cause the script to output something else in addition to just the plain OpenVPN command in dry run mode, though maybe if this was triggered by a flag maybe that would be ok.

Any other users care to weigh in?

**Comment by MattSurabian** [comment]
The more I've thought about this the more I'm not convinced this is the responsibility of this script. It's not directly an OpenVPN or ProXPN setting, but totally in the realm of the user's machine. 

I agree that there's a privacy issue here with apps leaking information but am not convinced that mitigating this kind of thing is what the user would expect from this script. 

That said, maybe we should mention this in the readme so folks are aware this could be happening?
