### ISSUE TITLE
Help text does not include protocol parameter

### ISSUE THREAD

**Issue by jbostrus** [MattSurabian/proxpn-bash-client#37]
As the subject implies, the help text when running "proxpn --help" does not detail that there is a protocol parameter that can be set. 

*edit: I'm not sure if I did this right since I've not used github much. I did a fork edit and pull request for this with a proposed change.

**Comment by MattSurabian** [comment]
Ah! Good catch, thanks.

**Comment by MattSurabian** [comment]
Thanks for the PR! Just released in 4.0.1
