### ISSUE TITLE
Exiting due to fatal error

### ISSUE THREAD

**Issue by kenthinson** [MattSurabian/proxpn-bash-client#39]
Hello. Running Ubuntu 16.04 in a lxc container. the host is proxmox 4.2
I downloaded and installed the script using the included install.sh
getting error:
Fri May 27 19:13:34 2016 us=350204 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
Fri May 27 19:13:34 2016 us=350216 Exiting due to fatal error

any help would be awesome thanks!

**Comment by kenthinson** [comment]
Never mind I found the solution here http://serverfault.com/questions/429461/no-tun-device-in-lxc-guest-for-openvpn you can close this.

**Comment by MattSurabian** [comment]
Thanks for updating this issue with the fix and glad you got it sorted out! Hopefully this will be helpful to someone with the same issue in future. Cheers.
