### ISSUE TITLE
Add --dry-run flag

### ISSUE THREAD

**Issue by MattSurabian** [MattSurabian/proxpn-bash-client#6]
Instead of prompting the user, asking whether they want to run the command expose a `--dry-run` flag users can pass to avoid making the actual VPN connection. If the proxpn command is run without `sudo` automatically enter `dry-run` mode regardless of the presence of the flag.

Per #5.

**Comment by Pysis868** [comment]
What would a dry run accomplish?  Only demonstrating that it can load and validate the configuration file?
